services:
  demakai-franken:
    container_name: demakai-franken
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - SERVER_NAME=:80
    ports:
      - "8003:80"
    volumes:
      - app-storage:/app/storage
      - app-database:/app/database
    networks:
      - postgres-stack_ai_net

  demakai-worker:
    container_name: demakai-worker
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - QUEUE_CONNECTION=database
    command: "php artisan queue:work --sleep=3 --tries=3 --max-time=3600"
    volumes:
      - app-storage:/app/storage
      - app-database:/app/database
    networks:
      - postgres-stack_ai_net

volumes:
  app-storage:
  app-database:

networks:
  postgres-stack_ai_net:
    external: true
