services:
  demakai-franken:
    container_name: demakai-franken
    restart: unless-stopped
    image: ghcr.io/muhshi/demakai:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - SERVER_NAME=:80
      - PYTHON_SEARCH_ENABLED=true
      - PYTHON_SEARCH_URL=http://demakai-python:8000
      - PYTHON_SEARCH_METHOD=sql
      - PYTHON_SEARCH_PROCESSING=none
    ports:
      - "8003:80"
    volumes:
      - app-storage:/app/storage
    depends_on:
      - demakai-python
    networks:
      - postgres-stack_ai_net

  demakai-worker:
    container_name: demakai-worker
    restart: unless-stopped
    image: ghcr.io/muhshi/demakai:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - QUEUE_CONNECTION=database
    command: "php artisan queue:work --sleep=3 --tries=3 --max-time=3600"
    volumes:
      - app-storage:/app/storage
    networks:
      - postgres-stack_ai_net

  demakai-python:
    container_name: demakai-python
    restart: unless-stopped
    build:
      context: ./python
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - postgres-stack_ai_net

volumes:
  app-storage:

networks:
  postgres-stack_ai_net:
    external: true
